// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJA43obML24mQx0K3Nfw_8MM-wzy2WAmM',
    appId: '1:327805065973:web:7c8116d44f19f9f18ac3bc',
    messagingSenderId: '327805065973',
    projectId: 'ont-helpdesk',
    authDomain: 'ont-helpdesk.firebaseapp.com',
    storageBucket: 'ont-helpdesk.firebasestorage.app',
    measurementId: 'G-H47FCEJR8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgAtqTjPGLB6ctHxMfn6el1zMooCRQpjQ',
    appId: '1:327805065973:android:9d88f23b053eac3f8ac3bc',
    messagingSenderId: '327805065973',
    projectId: 'ont-helpdesk',
    storageBucket: 'ont-helpdesk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj8DaSo8SBjEtV7uDtk7koiXqAGsTHrfM',
    appId: '1:327805065973:ios:5560a8d61bf844358ac3bc',
    messagingSenderId: '327805065973',
    projectId: 'ont-helpdesk',
    storageBucket: 'ont-helpdesk.firebasestorage.app',
    iosClientId: '327805065973-4b6c1r7so4l46jfosprin1jl48bjc982.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpdeskOnt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj8DaSo8SBjEtV7uDtk7koiXqAGsTHrfM',
    appId: '1:327805065973:ios:5560a8d61bf844358ac3bc',
    messagingSenderId: '327805065973',
    projectId: 'ont-helpdesk',
    storageBucket: 'ont-helpdesk.firebasestorage.app',
    iosClientId: '327805065973-4b6c1r7so4l46jfosprin1jl48bjc982.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpdeskOnt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJA43obML24mQx0K3Nfw_8MM-wzy2WAmM',
    appId: '1:327805065973:web:fe5e7631a8a7c8d28ac3bc',
    messagingSenderId: '327805065973',
    projectId: 'ont-helpdesk',
    authDomain: 'ont-helpdesk.firebaseapp.com',
    storageBucket: 'ont-helpdesk.firebasestorage.app',
    measurementId: 'G-68CK0R8WLV',
  );

}